config/routes.rb
Rails.application.routes.draw do
  resources :promo_items
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  # resources :line_items
  resources :carts
  resources :menu_items
  resources :employees
  resources :orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/contact", to: "main#contact"
  get "/home", to: "main#index"
  get "/menu", to: "main#menu"
  get "/promoitem", to: "main#promo_item"
  get "/login", to: "main#login"
  get "/orders", to: "main#orders"

  get "/employees", to: "employees#index"
  get "/menuitems", to: "menu_items#index"
  get "/promoitems", to: "promo_items#index"
  get "/newemployees", to: "employees#new"


  # get 'carts/:id' => "carts#show", as: "/carts"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  root "main#index"



end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  # has_many :line_items, dependent: :destroy
  has_many :carts, through: :line_items
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]

  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save!
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully created." }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :image, :price, :ispromo)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item) do |form| %>
  <% if menu_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :ispromo, style: "display: block" %>
    <%= form.check_box :ispromo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div id="<%= dom_id menu_item %>">
  <p>
    <strong>Name:</strong>
    <%= menu_item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu_item.description %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= menu_item.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu_item.price %>
  </p>

  <p>
    <strong>Ispromo:</strong>
    <%= menu_item.ispromo %>
  </p>

</div>

app/views/menu_items/edit.html.erb
<h1>Editing menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Show this menu item", @menu_item %> |
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menu items</h1>

<div id="menu_items">
  <% @menu_items.each do |menu_item| %>
    <%= render menu_item %>
    <p>
      <%= link_to "Show this menu item", menu_item %>
    </p>
  <% end %>
</div>

<%= link_to "New menu item", new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_item %>

<div>
  <%= link_to "Edit this menu item", edit_menu_item_path(@menu_item) %> |
  <%= link_to "Back to menu items", menu_items_path %>


  <%= button_to "Destroy this menu item", @menu_item, method: :delete %>
</div>