config/routes.rb
Rails.application.routes.draw do
  resources :promo_items
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  # resources :line_items
  resources :carts
  resources :menu_items
  resources :employees
  resources :orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/contact", to: "main#contact"
  get "/home", to: "main#index"
  get "/menu", to: "main#menu"
  get "/promoitem", to: "main#promo_item"
  get "/login", to: "main#login"
  get "/orders", to: "main#orders"

  get "/employees", to: "employees#index"
  get "/menuitems", to: "menu_items#index"
  get "/promoitems", to: "promo_items#index"
  get "/newemployees", to: "employees#new"


  # get 'carts/:id' => "carts#show", as: "/carts"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  root "main#index"



end

app/models/promo_item.rb
class PromoItem < ApplicationRecord
end

app/controllers/promo_items_controller.rb
class PromoItemsController < ApplicationController
  before_action :set_promo_item, only: %i[ show edit update destroy ]

  # GET /promo_items or /promo_items.json
  def index
    @promo_items = PromoItem.all
  end

  # GET /promo_items/1 or /promo_items/1.json
  def show
  end

  # GET /promo_items/new
  def new
    @promo_item = PromoItem.new
  end

  # GET /promo_items/1/edit
  def edit
  end

  # POST /promo_items or /promo_items.json
  def create
    @promo_item = PromoItem.new(promo_item_params)

    respond_to do |format|
      if @promo_item.save!
        format.html { redirect_to promo_item_url(@promo_item), notice: "Promo item was successfully created." }
        format.json { render :show, status: :created, location: @promo_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @promo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promo_items/1 or /promo_items/1.json
  def update
    respond_to do |format|
      if @promo_item.update(promo_item_params)
        format.html { redirect_to promo_item_url(@promo_item), notice: "Promo item was successfully updated." }
        format.json { render :show, status: :ok, location: @promo_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @promo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_items/1 or /promo_items/1.json
  def destroy
    @promo_item.destroy

    respond_to do |format|
      format.html { redirect_to promo_items_url, notice: "Promo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_item
      @promo_item = PromoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promo_item_params
      params.require(:promo_item).permit(:name, :description, :image, :price)
    end
end

app/helpers/promo_items_helper.rb
module PromoItemsHelper
end

app/views/promo_items/_form.html.erb
<%= form_with(model: promo_item) do |form| %>
  <% if promo_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(promo_item.errors.count, "error") %> prohibited this promo_item from being saved:</h2>

      <ul>
        <% promo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/promo_items/_promo_item.html.erb
<div id="<%= dom_id promo_item %>">
  <p>
    <strong>Name:</strong>
    <%= promo_item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= promo_item.description %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= promo_item.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= promo_item.price %>
  </p>

</div>

app/views/promo_items/edit.html.erb
<h1>Editing promo item</h1>

<%= render "form", promo_item: @promo_item %>

<br>

<div>
  <%= link_to "Show this promo item", @promo_item %> |
  <%= link_to "Back to promo items", promo_items_path %>
</div>

app/views/promo_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Promo items</h1>

<div id="promo_items">
  <% @promo_items.each do |promo_item| %>
    <%= render promo_item %>
    <p>
      <%= link_to "Show this promo item", promo_item %>
    </p>
  <% end %>
</div>

<%= link_to "New promo item", new_promo_item_path %>

app/views/promo_items/new.html.erb
<h1>New promo item</h1>

<%= render "form", promo_item: @promo_item %>

<br>

<div>
  <%= link_to "Back to promo items", promo_items_path %>
</div>

app/views/promo_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @promo_item %>

<div>
  <%= link_to "Edit this promo item", edit_promo_item_path(@promo_item) %> |
  <%= link_to "Back to promo items", promo_items_path %>

  <%= button_to "Destroy this promo item", @promo_item, method: :delete %>
</div>